apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-svc
  name: {{ .Release.Name }}-webapp-svc
spec:
  ports:
  - name: webapp-svc
    port: 80
    protocol: TCP
    targetPort: 80
    #    nodePort: 31000
  selector:
    app: logindep
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
